<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="LiteDB" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TrainDude.Queries.Contracts\TrainDude.Queries.Contracts.csproj" />
        <ProjectReference Include="..\TrainDude.Queries.Data\TrainDude.Queries.Data.csproj"/>
    </ItemGroup>

</Project>
