// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainDude.Commands.Data;

#nullable disable

namespace TrainDude.Commands.Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260805201056_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Line", b =>
                {
                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("LineLetter")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("LineNumber", "LineLetter");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Radius", b =>
                {
                    b.Property<int>("RadiusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadiusId"));

                    b.Property<int>("Minimum")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("RadiusId");

                    b.ToTable("Radii");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentId"));

                    b.Property<double?>("NominalLength")
                        .HasColumnType("float");

                    b.HasKey("SegmentId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.SegmentExtreme", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("bit");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("SegmentId", "IsEnd");

                    b.HasIndex("StationId");

                    b.ToTable("SegmentExtremes");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.SegmentVertex", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<int>("OrdinalId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "TrainDude.Commands.Data.Entities.SegmentVertex.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");
                        });

                    b.HasKey("SegmentId", "OrdinalId");

                    b.ToTable("SegmentVertices");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePolish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePolishOld")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "TrainDude.Commands.Data.Entities.Station.Location#Location", b1 =>
                        {
                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");
                        });

                    b.HasKey("StationId");

                    b.HasIndex("NameGerman")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Trip", b =>
                {
                    b.Property<int>("TripNumber")
                        .HasColumnType("int");

                    b.HasKey("TripNumber");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.SegmentExtreme", b =>
                {
                    b.HasOne("TrainDude.Commands.Data.Entities.Segment", "Segment")
                        .WithMany("Extremes")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDude.Commands.Data.Entities.Station", "Station")
                        .WithMany("SegmentExtremes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segment");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.SegmentVertex", b =>
                {
                    b.HasOne("TrainDude.Commands.Data.Entities.Segment", "Segment")
                        .WithMany("Vertices")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Segment", b =>
                {
                    b.Navigation("Extremes");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("TrainDude.Commands.Data.Entities.Station", b =>
                {
                    b.Navigation("SegmentExtremes");
                });
#pragma warning restore 612, 618
        }
    }
}
