<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\analyzers\TrainDude.Architecture.Analyzers\TrainDude.Architecture.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
    <ProjectReference Include="..\TrainDude.Shared.Values\TrainDude.Shared.Values.csproj"/>
  </ItemGroup>
</Project>
