<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="Marten" Version="9.24.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainDude.Commands.Requests\TrainDude.Commands.Requests.csproj" />
      <ProjectReference Include="..\TrainDude.Domain\TrainDude.Domain.csproj" />
    </ItemGroup>

</Project>