<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainDude.Commands.Requests\TrainDude.Commands.Requests.csproj" />
      <ProjectReference Include="..\TrainDude.Commands.Data\TrainDude.Commands.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\radii_seed.yml" />
      <EmbeddedResource Include="Resources\lines_seed.yml" />
      <EmbeddedResource Include="Resources\segments_seed.yml" />
      <EmbeddedResource Include="Resources\stations_seed.yml" />
      <EmbeddedResource Include="Resources\trips_seed.yml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="stylecop.json" />
    </ItemGroup>
    
</Project>