<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Lines\" />
    <Folder Include="Radii\" />
    <Folder Include="Segments\" />
    <Folder Include="Settings\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TrainDude.Features.Lines\TrainDude.Features.Lines.csproj" />
    <ProjectReference Include="..\TrainDude.Features.Radii\TrainDude.Features.Radii.csproj" />
    <ProjectReference Include="..\TrainDude.Features.Segments\TrainDude.Features.Segments.csproj" />
    <ProjectReference Include="..\TrainDude.Features.Settings\TrainDude.Features.Settings.csproj" />
    <ProjectReference Include="..\TrainDude.Features.Stations\TrainDude.Features.Stations.csproj" />
    <ProjectReference Include="..\TrainDude.Features.Trips\TrainDude.Features.Trips.csproj" />
  </ItemGroup>
</Project>