// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrainDude.Data.Migrations
{
    [DbContext(typeof(NetworkDbContext))]
    [Migration("20260728191804_SegmentVertices")]
    partial class SegmentVertices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrainDude.Data.Models.Radius", b =>
                {
                    b.Property<int>("RadiusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("RadiusId");

                    b.ToTable("Radii");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NominalLength")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("TrainDude.Data.Models.SegmentExtreme", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SegmentId", "IsEnd");

                    b.HasIndex("StationId");

                    b.ToTable("SegmentExtremes");
                });

            modelBuilder.Entity("TrainDude.Data.Models.SegmentVertexLocation", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdinalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentId", "OrdinalId");

                    b.ToTable("SegmentVertexLocation");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolish")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolishOld")
                        .HasColumnType("TEXT");

                    b.HasKey("StationId");

                    b.HasIndex("NameGerman")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainDude.Data.Models.StationLocation", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("StationId");

                    b.ToTable("StationLocation");
                });

            modelBuilder.Entity("TrainDude.Data.Models.SegmentExtreme", b =>
                {
                    b.HasOne("TrainDude.Data.Models.Segment", "Segment")
                        .WithMany("Extremes")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDude.Data.Models.Station", "Station")
                        .WithMany("SegmentExtremes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segment");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Data.Models.SegmentVertexLocation", b =>
                {
                    b.HasOne("TrainDude.Data.Models.Segment", "Segment")
                        .WithMany("Vertices")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("TrainDude.Data.Models.StationLocation", b =>
                {
                    b.HasOne("TrainDude.Data.Models.Station", "Station")
                        .WithOne("Location")
                        .HasForeignKey("TrainDude.Data.Models.StationLocation", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Segment", b =>
                {
                    b.Navigation("Extremes");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Station", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("SegmentExtremes");
                });
#pragma warning restore 612, 618
        }
    }
}
