// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainDude.Data;

#nullable disable

namespace TrainDude.Data.Migrations
{
    [DbContext(typeof(NetworkDbContext))]
    [Migration("20260731110822_TableRename")]
    partial class TableRename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrainDude.Data.Entities.Line", b =>
                {
                    b.Property<string>("LineId")
                        .HasColumnType("TEXT");

                    b.HasKey("LineId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.LineSegment", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineId")
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentId", "LineId");

                    b.HasIndex("LineId");

                    b.ToTable("LineSegment");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Radius", b =>
                {
                    b.Property<int>("RadiusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("RadiusId");

                    b.ToTable("Radii");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NominalLength")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.SegmentExtreme", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SegmentId", "IsEnd");

                    b.HasIndex("StationId");

                    b.ToTable("SegmentExtremes");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.SegmentVertexLocation", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdinalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentId", "OrdinalId");

                    b.ToTable("SegmentVertexLocation");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolish")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolishOld")
                        .HasColumnType("TEXT");

                    b.HasKey("StationId");

                    b.HasIndex("NameGerman")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.StationLocation", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("StationId");

                    b.ToTable("StationLocation");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.LineSegment", b =>
                {
                    b.HasOne("TrainDude.Data.Entities.Line", "Line")
                        .WithMany("Segments")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainDude.Data.Entities.Segment", "Segment")
                        .WithMany("Lines")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.SegmentExtreme", b =>
                {
                    b.HasOne("TrainDude.Data.Entities.Segment", "Segment")
                        .WithMany("Extremes")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDude.Data.Entities.Station", "Station")
                        .WithMany("SegmentExtremes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segment");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.SegmentVertexLocation", b =>
                {
                    b.HasOne("TrainDude.Data.Entities.Segment", "Segment")
                        .WithMany("Vertices")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.StationLocation", b =>
                {
                    b.HasOne("TrainDude.Data.Entities.Station", "Station")
                        .WithOne("Location")
                        .HasForeignKey("TrainDude.Data.Entities.StationLocation", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Line", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Segment", b =>
                {
                    b.Navigation("Extremes");

                    b.Navigation("Lines");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("TrainDude.Data.Entities.Station", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("SegmentExtremes");
                });
#pragma warning restore 612, 618
        }
    }
}
