// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrainDude.Data.Migrations
{
    [DbContext(typeof(NetworkDbContext))]
    [Migration("20260725153221_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrainDude.Data.Models.Radius", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Radii");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NominalLength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TrainDude.Data.Models.RouteEnd", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteId", "IsFinish");

                    b.HasIndex("StationId");

                    b.ToTable("RouteEnd");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolish")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePolishOld")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameGerman")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainDude.Data.Models.RouteEnd", b =>
                {
                    b.HasOne("TrainDude.Data.Models.Route", "Route")
                        .WithMany("Ends")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDude.Data.Models.Station", "Station")
                        .WithMany("RouteEnds")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Station", b =>
                {
                    b.OwnsOne("TrainDude.Data.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("StationId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Route", b =>
                {
                    b.Navigation("Ends");
                });

            modelBuilder.Entity("TrainDude.Data.Models.Station", b =>
                {
                    b.Navigation("RouteEnds");
                });
#pragma warning restore 612, 618
        }
    }
}
