<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.DotNet.HotReload.WebAssembly.Browser" />
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainDude.Commands.Contracts\TrainDude.Commands.Contracts.csproj" />
      <ProjectReference Include="..\TrainDude.Queries.Contracts\TrainDude.Queries.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\appsettings.json" />
      <_ContentIncludedByDefault Remove="Validation\TemplatedValidationMessage.razor" />
    </ItemGroup>

</Project>
