<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
      <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainDude.Application.Requests\TrainDude.Application.Requests.csproj" />
      <ProjectReference Include="..\TrainDude.Data\TrainDude.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\radii_seed.yml" />
      <EmbeddedResource Include="Resources\lines_seed.yml" />
      <EmbeddedResource Include="Resources\segments_seed.yml" />
      <EmbeddedResource Include="Resources\stations_seed.yml" />
      <EmbeddedResource Include="Resources\trips_seed.yml" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="FluentValidation">
        <HintPath>..\..\..\..\.nuget\packages\fluentvalidation\12.1.1\lib\net8.0\FluentValidation.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>