<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainDude.Commands.Data\TrainDude.Commands.Data.csproj" />
      <ProjectReference Include="..\TrainDude.Queries.Data\TrainDude.Queries.Data.csproj" />
    </ItemGroup>

</Project>
