// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainDude.Queries.Data;

#nullable disable

namespace TrainDude.Queries.Data.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20260805155446_AFewSmallFixesForTrivialIssues")]
    partial class AFewSmallFixesForTrivialIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrainDude.Queries.Data.Entities.Radius", b =>
                {
                    b.Property<int>("RadiusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("RadiusId");

                    b.ToTable("Radii");
                });

            modelBuilder.Entity("TrainDude.Queries.Data.Entities.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ASegmentStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BSegmentStationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NominalLength")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentId");

                    b.HasIndex("ASegmentStationId");

                    b.HasIndex("BSegmentStationId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("TrainDude.Queries.Data.Entities.SegmentStation", b =>
                {
                    b.Property<int>("SegmentStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "TrainDude.Queries.Data.Entities.SegmentStation.Location#Location", b1 =>
                        {
                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("SegmentStationId");

                    b.ToTable("SegmentStation");
                });

            modelBuilder.Entity("TrainDude.Queries.Data.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGermanNew")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "TrainDude.Queries.Data.Entities.Station.Location#Location", b1 =>
                        {
                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("StationId");

                    b.HasIndex("NameGerman")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainDude.Queries.Data.Entities.Segment", b =>
                {
                    b.HasOne("TrainDude.Queries.Data.Entities.SegmentStation", "A")
                        .WithMany()
                        .HasForeignKey("ASegmentStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainDude.Queries.Data.Entities.SegmentStation", "B")
                        .WithMany()
                        .HasForeignKey("BSegmentStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A");

                    b.Navigation("B");
                });
#pragma warning restore 612, 618
        }
    }
}
